version: "3.9"
services:
  web:
    image: urnau/app1-php:prod-nginx-php-fpm8.2.3
    container_name: web
    build:
      context: .
      dockerfile: ./docker/Dockerfile
      args:
        PHP_VERSION: '8.2.4-fpm-bullseye'
    volumes:
      - ./app:/var/www/app
    ports:
      - "80:80" #http
      - "443:443" #https
    networks:
        - laravel

  database:
    image: postgres
    container_name: database
    platform: linux/x86_64
    restart: unless-stopped
    environment:
        POSTGRES_DB: laravel
        POSTGRES_USER: postgres
        POSTGRES_PASSWORD: postgres
    volumes:
      - ./docker/postgres/dbdata:/var/lib/postgresql/data
    ports:
        - "5432:5432"
    networks:
        - laravel

  redis:
        container_name: redis
        image: redis:latest
        networks:
            - laravel
                    
networks:
    laravel:
        driver: bridge